### PR TITLE
Add interface to obtain LWP number in a portable way.

### PR DESCRIPTION
**Pull request by abh3**
Ready for review/modification.

### CODE REVIEW

**Comment by ktlim** [comment]
This looks fine.  I had to read up about thread_local storage duration -- but doesn't that mean that we could go beyond this and easily add an MDC by instantiating a thread_local object?

**Comment by andy-slac** [comment]
I'm not quite happy with the interface itself (especially macro), but it does not really matter. What we actually need is a configurable way to instantiate MDC for new threads and this code does not solve that. The code to discover LWP ID is useful and can be reused of course. I propose we do not merge this branch, instead I'm going to open a new ticket to work on MDC part and incorporate pieces of this code into a new ticket.

**Comment by abh3** [comment]
I guess I'm not sure why a simple variable that holds a value is a problematic interface. The macro was there simply to get around LSST name space wordiness and protect code from interface changes. As for adding an MDC, quite correct now that dynamic initialization is supported in glibc.

**Comment by andy-slac** [comment]
My point is that this interface is not going to be used so there is no reason to expose it and pollute namespace with macros. We'll do everything through MDC, and for that we'll only need a function to return LWP ID. BTW, the ticket was "Implement **function** that generates threadId for logging" :)

**Comment by abh3** [comment]
Well, technically a variable can be considered a function and can even be made to look like one :-)

**Pull request closed without merging**
